version: "3.9"

services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile.main
    environment:
      CRDBOARD_BASE_DIR: /app
      CRDBOARD_DATA_DIR: /app/data
      CRDBOARD_SECRET_KEY: dev-secret
      CRDBOARD_TABLE_ACCESS_SECRET: table-dev-secret
      CRDBOARD_TABLE_SERVER_HOST: localhost
      CRDBOARD_TABLE_SERVER_BASE_PORT: 7000
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data

  table-server-1:
    build:
      context: .
      dockerfile: Dockerfile.table-server
    environment:
      CRDBOARD_TABLE_ID: 1
      CRDBOARD_TABLE_ACCESS_SECRET: table-dev-secret
      CRDBOARD_TABLE_DB_DIR: /app/data/tables
    ports:
      - "7001:7000"
    volumes:
      - ./data:/app/data
